steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Prsima
        id: Prsima
        uses: bridgecrewio/checkov-action@master 
        env:
          PRISMA_API_URL: https://api.ind.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
